### PR TITLE
Service advisor drupal backend

### PR DESCRIPTION
**Pull request by fmann**
Merging recent changes to support the Drupal backend into a new branch

### CODE REVIEW

**Comment by lkysow** [comment]
Is the plan to get rid of the current way we deploy the service? This PR deletes all the code for generating the current website.

**Comment by PeaceGeeksProjects** [comment]
Hi Luke

I am out of town this week, but I am going to try to organize a meeting for
the week of April 4 to go though everything. Can you clarify what you mean
by PR?

_Renee Black_,
_Executive Director_
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
_p._ 778-235-7458 | _e._ renee@peacegeeks.org
_skype._ reneeontheroad

**Comment by lkysow** [comment]
Oh by PR I mean pull request, this set of changes.

**Comment by fmann** [comment]
There is a different backend and the schema / behaviour is starting to change in ways incompatible with the old approach.  So... yeah, this branch has started to drop some of the stuff that isn't likely to be useful going forward.

**Comment by lkysow** [comment]
@fmann :+1:  makes sense, just want to confirm we're going that way on purpose. There's still the http://advisor.unhcr.jo/ website running so my only fear is we merge all this into master and then something goes wrong with the legacy site or we need to make an update and suddenly that's a lot harder. We can talk about this at our upcoming meeting for sure.

**Pull request merged**
