### PR TITLE
Update filters ui

### PR DESCRIPTION
**Pull request by Jareechang**
@lkysow @amyngai @tuckerbuchy! Hey guys, This is the new code for the new navigation bar UX. 
Please review :) Thank you!

### CODE REVIEW

**Comment by amyngai** [comment]
Just reviewing for design :)
- the panel also needs to be a bit faster. Use this as a reference  https://codyhouse.co/demo/3d-bold-navigation/index.html
- filters bar should appear from below the top black bar
  kinda like this, but it's weird that the map zoom is on top...
  (just added z-index to stuff)
  navbar-ontop
- Add a box shadow to mobile
- Also edit the box shadow on web version to this
  `box-shadow: 0px 5px 100px rgba(0, 0, 0, 0.15);` (both mobile and web should be the same code)
- Filters should also have a bg colour of `#F8FAFB` (both mobile and web)
- `ok` button should have `margin-bottom: 10px;`

thanks! :'D

**Comment by Jareechang** [comment]
@amyngai, i'll have a look at this. Nice reference site, just what I needed :)

**Comment by amyngai** [comment]
:+1:

**Comment by Jareechang** [comment]
i've made the changes @amyngai, let me know if I missed anything!

**Comment by amyngai** [comment]
missing the background colour for filters
`background-color: #F8FAFB;`

else, it looks/feels perfect :ok_hand: great stuff!

**Comment by Jareechang** [comment]
interesting, I thought I did added the background :open_mouth:
do you mean the filter pills ? or the filter panel ?

**Comment by amyngai** [comment]
ah! i found it, just a media query. It's not showing up on web. It's good on mobile. :stuck_out_tongue:

**Comment by Jareechang** [comment]
great catch! it should be fixed now!

**Comment by lkysow** [comment]
@Jareechang I added a commit that simplifies some of the code we had for toggling the overlay and for closing the overlay when you click outside the overlay.

Everything looks great but there's an important issue we need to fix before this can be merged. When you add lots of filter on mobile, the "apply" button gets hidden and you can't close the overlay. This happens because the overlay is now absolutely positioned. Is there a way to remove this absolute positioning on mobile? When I remove the `top:` css rule on `#filters` the issue doesn't appear anymore.

image

**Comment by Jareechang** [comment]
yes @lkysow, you are right. 
I must of been possessed by the hack ghost as I was writing that, your solution looks less convoluted. nice! 

i've also added the toggle for the dark tint overlay on mobile/tablets devices into the function.

**Comment by lkysow** [comment]
Cool so only thing left to fix is the "Apply" button being hidden due to the absolute positioning

**Comment by Jareechang** [comment]
So, everything should be updated now. 

In addition, i've added a click event on the overlay to toggle its active class when you click on the actual overlay.

Let me know if these changes resolves the issues.

**Comment by lkysow** [comment]
:+1: :santa: :christmas_tree:

**Pull request merged**
