### PR TITLE
Search

### PR DESCRIPTION
**Pull request by Jareechang**
@lkysow, I moved the angularJS files from index.js into a separate folder so we can work off that. Also, added some files to .gitignore. Let me know what you think.

### CODE REVIEW

**Comment by lkysow** [comment]
Cool, I like keeping it under `src`. Can we call the folder `src/angular` instead of `src/angular-js-version`

**Comment by Jareechang** [comment]
Sure thing, src/angular it is then. do you want me to change it and just
push to the search branch ?

**Comment by lkysow** [comment]
Yep, you can push to the search branch on cynthialee and then click "merge" here! :+1:

**Comment by Jareechang** [comment]
cool.

**Pull request merged**
